[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center", "--outputs", "all"]
set = false 


[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '../hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '../kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '../rofi/colors.rasi'

[templates.waybar]
input_path = 'templates/colors.css' 
output_path = '../waybar/colors.css'
post_hook = 'pkill waybar; waybar &'
