[config.wallpaper]

command=''
set = false 

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/colors.rasi'

[templates.waybar]
input_path = 'templates/colors.css' 
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; waybar &'

[templates.swaync]
input_path = "templates/colors.css"
output_path = "~/.config/swaync/colors.css"

[templates.gtk3]
input_path = "templates/matugen-gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = 'templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.tmux]
input_path = 'templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'
